### ISSUE TITLE
Extend dlldump and procdump with exifinfo

### ISSUE THREAD

**Issue by iScripters** [SolventLobotomy/Lobotomy#1]
**Venhuizen created an issue 2015-04-07**
Extend dlldump and procdump with exifinfo

https://www.virustotal.com/en/file/45f3b06cfb72ff8fc49fbb7076561b4ebf67a0953b1472ebeaec9d48c8c9dc92/analysis/ see tab 'File Detail'

**Comment by wvenhuizen** [comment]
moddump, dlldump and procdump have exifinfo routine.
closed
